#!/bin/bash
BRANCH="main"

while read oldrev newrev ref
do
	# only checking out the master (or whatever branch you would like to deploy)
	if [ "$ref" = "refs/heads/$BRANCH" ];
	then
		echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
        git fetch
		git checkout -f $BRANCH
        make install
	else
		echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server. Please push to ${BRANCH} if you wish your changes to get deployed."
	fi
done